services:
  postgres:
    image: postgres:18
    container_name: stocks_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data-stocks:/var/lib/postgresql/data
    networks:
      - stocks_net
    ports:
      - "10.0.0.1:5432:5432"

  redis:
    image: redis:alpine
    container_name: stocks_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env
    networks:
      - stocks_net
    ports:
      - "10.0.0.1:6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stocks_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    networks: [stocks_net, edge]

networks:
  stocks_net:
    driver: bridge
  edge:
    external: true